# Generated by Django 4.2.1 on 2023-10-23 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11)),
                ('telefone', models.CharField(blank=True, max_length=11, null=True)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('data_nascimento', models.DateField()),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pessoa', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='acesso.pessoa')),
                ('matricula', models.CharField(max_length=5)),
                ('cargo', models.CharField(max_length=256)),
                ('turno', models.CharField(choices=[('M', 'Manhã'), ('T', 'Tarde'), ('N', 'Noite')], max_length=1)),
            ],
            bases=('acesso.pessoa',),
        ),
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='acesso.pessoa')),
                ('tipo', models.CharField(choices=[('E', 'Escola'), ('D', 'Delivery'), ('V', 'Visita técnica')], max_length=1)),
            ],
            bases=('acesso.pessoa',),
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=12)),
                ('modelo', models.CharField(max_length=64)),
                ('ano', models.IntegerField()),
                ('cor', models.CharField(max_length=64)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acesso.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroAcessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_entrada', models.DateTimeField()),
                ('data_hora_saida', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('E', 'Em andamento'), ('F', 'Finalizado')], max_length=1)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acesso.pessoa')),
                ('veiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='acesso.veiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(max_length=256)),
                ('numero', models.CharField(blank=True, max_length=8, null=True)),
                ('bairro', models.CharField(max_length=256)),
                ('cidade', models.CharField(max_length=256)),
                ('estado', models.CharField(max_length=256)),
                ('cep', models.CharField(max_length=8)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acesso.pessoa')),
            ],
        ),
    ]
