# Generated by Django 4.2.1 on 2023-10-24 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acesso', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegistroAcessor',
            new_name='RegistroAcesso',
        ),
    ]
